name: Build and Push Docker Image

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: quay.io/takinosh/todo-demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle

    - name: Build with Maven
      run: mvn package

    - name: test result
      run: |
        ls -lath . 
        ls -R target

    - name: Login to Quay.io
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_IO_USERNAME }}
        password: ${{ secrets.QUAY_IO_PASSWORD }}

    - name: Build Docker Image
      run: docker build -f src/main/docker/Dockerfile.jvm  -t $IMAGE_NAME .

    #- name: Push Docker Image
    #  run: docker push $IMAGE_NAME
