name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: oracle

    - name: Set docker image tag env
      run: echo "POSTGRES_URL='jdbc:postgresql://todo-database:5432/todo-database'" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn -B clean package -DskipTests=true

    - name: Test with Maven
      run: mvn -B test
